SUMMARY = "Gazebo Classic version 11"
DESCRIPTION = "${SUMMARY}"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=622f4fcdd9e66304dcb89897348be7b0"

SRC_URI = "git://github.com/gazebosim/gazebo-classic;branch=gazebo11_11.13.0;nobranch=1;protocol=https"
SRCREV = "fbb3d12273b02a382085ebf1f1ba72c4da315112"

SRC_URI:append:class-native = " file://0000-cmake-native.patch"

S = "${WORKDIR}/git"

DEPENDS = " \
    freeimage \
    protobuf \
    protobuf-native \
    ogre \
    hdf5 \
    libtinyxml2 \
    ffmpeg \
    gts \
    bullet \
    sdformat9 \
    tbb \
    libtar \
    libusb1 \
    python3-native \
    python3 \
    gz-cmake2 \
    gz-common3 \
    gz-msgs5 \
    gz-math6 \
    gz-transport8 \
    gz-fuel-tools4 \
"

DEPENDS:append:class-target = " \
    qwt-qt5 \
    dart-physics \
    gazebo11-native \
"

RDEPENDS:${PN} = " \
    ogre-dev \
"

inherit cmake pkgconfig cmake_qt5

EXTRA_OECMAKE = " \
    -DBUILD_TESTING=OFF \
    -DFREEIMAGE_RUNS=FAILED_TO_RUN \
    -DFREEIMAGE_RUNS__TRYRUN_OUTPUT='' \
    -DPython3_FIND_STRATEGY=LOCATION \
"

EXTRA_OECMAKE:append:class-native = " \
    -DINSTALL_GAZEBOMSGS_OUT_EXECUTABLE:BOOL=ON \
"

EXTRA_OECMAKE:append:class-target = " \
    -DGAZEBOMSGS_OUT_EXECUTABLE=${WORKDIR}/recipe-sysroot-native/usr/bin/gazebomsgs_out \
    -DPROTOBUF_PROTOC_EXECUTABLE=${WORKDIR}/recipe-sysroot-native/usr/bin/protoc \
    -DPython_LIBRARY:FILEPATH=${WORKDIR}/recipe-sysroot/usr/lib \
    -DPython_EXECUTABLE:FILEPATH=${WORKDIR}/recipe-sysroot-native/usr/bin/python3-native/python3 \
    -DSSE2_FOUND=FALSE \
    -DSSE3_FOUND=FALSE \
    -DSSSE3_FOUND=FALSE \
    -DSSE4_1_FOUND=FALSE \
    -DSSE4_2_FOUND=FALSE \
    -DENABLE_SSE4=FALSE \
"

FILES:${PN}:append = " \
    /usr/share/gazebo-11 \
    /usr/share/gazebo \
    /usr/share/gazebo-11/setup.sh \
    /usr/share/gazebo-11/setup.bash \
    /usr/share/gazebo-11/media \
    /usr/share/gazebo-11/worlds \
    /usr/share/gazebo-11/models \
    /usr/share/gazebo-11/media/audio \
    /usr/share/gazebo-11/media/dem \
    /usr/share/gazebo-11/media/fonts \
    /usr/share/gazebo-11/media/gui \
    /usr/share/gazebo-11/media/materials \
    /usr/share/gazebo-11/media/models \
    /usr/share/gazebo-11/media/rtshaderlib \
    /usr/share/gazebo-11/media/skyx \
    /usr/share/gazebo-11/media/audio/cheer.wav \
    /usr/share/gazebo-11/media/audio/cheer.ogg \
    /usr/share/gazebo-11/media/audio/cheer.mp3 \
    /usr/share/gazebo-11/media/dem/volcano.tif \
    /usr/share/gazebo-11/media/fonts/arial.ttf \
    /usr/share/gazebo-11/media/fonts/console.ttf \
    /usr/share/gazebo-11/media/fonts/font_arial.png \
    /usr/share/gazebo-11/media/fonts/font_matisse_itc.png \
    /usr/share/gazebo-11/media/fonts/Gazebo.fontdef \
    /usr/share/gazebo-11/media/gui/looknfeel \
    /usr/share/gazebo-11/media/gui/schemes \
    /usr/share/gazebo-11/media/gui/imagesets \
    /usr/share/gazebo-11/media/gui/fonts \
    /usr/share/gazebo-11/media/gui/looknfeel/Falagard.xsd \
    /usr/share/gazebo-11/media/gui/looknfeel/OgreTray.looknfeel \
    /usr/share/gazebo-11/media/gui/looknfeel/TaharezLook.looknfeel \
    /usr/share/gazebo-11/media/gui/looknfeel/Vanilla.looknfeel \
    /usr/share/gazebo-11/media/gui/looknfeel/WindowsLook.looknfeel \
    /usr/share/gazebo-11/media/gui/looknfeel/Gazebo.looknfeel \
    /usr/share/gazebo-11/media/gui/schemes/Animation.xsd \
    /usr/share/gazebo-11/media/gui/schemes/CEGUIConfig.xsd \
    /usr/share/gazebo-11/media/gui/schemes/GUILayout.xsd \
    /usr/share/gazebo-11/media/gui/schemes/GUIScheme.xsd \
    /usr/share/gazebo-11/media/gui/schemes/Demo8.scheme \
    /usr/share/gazebo-11/media/gui/schemes/OgreTray.scheme \
    /usr/share/gazebo-11/media/gui/schemes/TaharezLook.scheme \
    /usr/share/gazebo-11/media/gui/schemes/TaharezLookWidgetAliases.scheme \
    /usr/share/gazebo-11/media/gui/schemes/TaharezLookWidgets.scheme \
    /usr/share/gazebo-11/media/gui/schemes/VanillaSkin.scheme \
    /usr/share/gazebo-11/media/gui/schemes/WindowsLook.scheme \
    /usr/share/gazebo-11/media/gui/schemes/WindowsLookWidgets.scheme \
    /usr/share/gazebo-11/media/gui/schemes/GazeboSkin.scheme \
    /usr/share/gazebo-11/media/gui/imagesets/Imageset.xsd \
    /usr/share/gazebo-11/media/gui/imagesets/DriveIcons.imageset \
    /usr/share/gazebo-11/media/gui/imagesets/DriveIcons.png \
    /usr/share/gazebo-11/media/gui/imagesets/FairChar.imageset \
    /usr/share/gazebo-11/media/gui/imagesets/FairChar.tga \
    /usr/share/gazebo-11/media/gui/imagesets/GPN-2000-001437.tga \
    /usr/share/gazebo-11/media/gui/imagesets/logo.png \
    /usr/share/gazebo-11/media/gui/imagesets/OgreTray.imageset \
    /usr/share/gazebo-11/media/gui/imagesets/OgreTrayImages.png \
    /usr/share/gazebo-11/media/gui/imagesets/ReadMe.txt \
    /usr/share/gazebo-11/media/gui/imagesets/TaharezLook.imageset \
    /usr/share/gazebo-11/media/gui/imagesets/TaharezLook.tga \
    /usr/share/gazebo-11/media/gui/imagesets/Vanilla.imageset \
    /usr/share/gazebo-11/media/gui/imagesets/vanilla.tga \
    /usr/share/gazebo-11/media/gui/imagesets/WindowsLook.imageset \
    /usr/share/gazebo-11/media/gui/imagesets/WindowsLook.tga \
    /usr/share/gazebo-11/media/gui/imagesets/gazebo.tga \
    /usr/share/gazebo-11/media/gui/imagesets/Gazebo.imageset \
    /usr/share/gazebo-11/media/gui/fonts/Font.xsd \
    /usr/share/gazebo-11/media/gui/fonts/DejaVuSans-10.font \
    /usr/share/gazebo-11/media/gui/fonts/DejaVuSans.ttf \
    /usr/share/gazebo-11/media/gui/fonts/FairChar-30.font \
    /usr/share/gazebo-11/media/gui/fonts/fkp-16.font \
    /usr/share/gazebo-11/media/gui/fonts/fkp.de.pcf \
    /usr/share/gazebo-11/media/materials/programs \
    /usr/share/gazebo-11/media/materials/scripts \
    /usr/share/gazebo-11/media/materials/textures \
    /usr/share/gazebo-11/media/materials/programs/ambient_one_texture_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/blur.glsl \
    /usr/share/gazebo-11/media/materials/programs/camera_distortion_map_fs.glsl \
    /usr/share/gazebo-11/media/materials/programs/camera_distortion_map_vs.glsl \
    /usr/share/gazebo-11/media/materials/programs/camera_lens_flare_fs.glsl \
    /usr/share/gazebo-11/media/materials/programs/camera_lens_flare_vs.glsl \
    /usr/share/gazebo-11/media/materials/programs/camera_noise_gaussian_fs.glsl \
    /usr/share/gazebo-11/media/materials/programs/camera_noise_gaussian_vs.glsl \
    /usr/share/gazebo-11/media/materials/programs/CreaseShadingFP.glsl \
    /usr/share/gazebo-11/media/materials/programs/deform_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deform_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/depth_map.frag \
    /usr/share/gazebo-11/media/materials/programs/depth_map.vert \
    /usr/share/gazebo-11/media/materials/programs/depth_normals_map.frag \
    /usr/share/gazebo-11/media/materials/programs/depth_normals_map.vert \
    /usr/share/gazebo-11/media/materials/programs/depth_points_map.frag \
    /usr/share/gazebo-11/media/materials/programs/depth_points_map.vert \
    /usr/share/gazebo-11/media/materials/programs/directional_shadow_receiver_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/directional_shadow_receiver_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/GBufferFP.glsl \
    /usr/share/gazebo-11/media/materials/programs/GBufferVP.glsl \
    /usr/share/gazebo-11/media/materials/programs/grid_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/grid_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/laser_1st_pass_dbg.frag \
    /usr/share/gazebo-11/media/materials/programs/laser_1st_pass.frag \
    /usr/share/gazebo-11/media/materials/programs/laser_1st_pass.vert \
    /usr/share/gazebo-11/media/materials/programs/laser_2nd_pass.frag \
    /usr/share/gazebo-11/media/materials/programs/laser_2nd_pass.vert \
    /usr/share/gazebo-11/media/materials/programs/ModulateFP.glsl \
    /usr/share/gazebo-11/media/materials/programs/NoFilterFP.glsl \
    /usr/share/gazebo-11/media/materials/programs/oculus.cg \
    /usr/share/gazebo-11/media/materials/programs/OculusDistortionFragment.glsl \
    /usr/share/gazebo-11/media/materials/programs/OculusDistortionVertex.glsl \
    /usr/share/gazebo-11/media/materials/programs/perpixel_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/perpixel_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/plain_color_fs.glsl \
    /usr/share/gazebo-11/media/materials/programs/plain_color_vs.glsl \
    /usr/share/gazebo-11/media/materials/programs/point_light_shadow_demo_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/point_light_shadow_demo_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/point_receiver_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/point_receiver_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/projector.frag \
    /usr/share/gazebo-11/media/materials/programs/projector.vert \
    /usr/share/gazebo-11/media/materials/programs/shadow_caster_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/shadow_caster_ignore_heightmap_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/shadow_caster_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/StdQuad_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/spotlight_shadow_demo_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/spotlight_shadow_demo_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/spot_shadow_receiver_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/spot_shadow_receiver_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/wide_lens_map_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/wide_lens_map_vs.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/ssao_blurx.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/ssao_blury.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/ssao_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/ssao_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/vpl_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/vpl_lbuffer_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/vpl_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/RSM_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/RSM_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/deferred_shading \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/deferred_lighting \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/deferred_shading/ambient_ps.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/deferred_shading/light_material_ps.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/deferred_shading/light_material_vs.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/deferred_shading/ShadowCaster_fp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/deferred_shading/ShadowCaster_vp.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/deferred_shading/vs.glsl \
    /usr/share/gazebo-11/media/materials/programs/deferred_rendering/deferred_lighting/ambient_ps.glsl \
    /usr/share/gazebo-11/media/materials/scripts/blur.compositor \
    /usr/share/gazebo-11/media/materials/scripts/blur.material \
    /usr/share/gazebo-11/media/materials/scripts/CreaseShading.compositor \
    /usr/share/gazebo-11/media/materials/scripts/CreaseShading.material \
    /usr/share/gazebo-11/media/materials/scripts/deferred.compositor \
    /usr/share/gazebo-11/media/materials/scripts/deferred_post.material \
    /usr/share/gazebo-11/media/materials/scripts/deferred_post_minilight.material \
    /usr/share/gazebo-11/media/materials/scripts/deferred_post.program \
    /usr/share/gazebo-11/media/materials/scripts/distortion.compositor \
    /usr/share/gazebo-11/media/materials/scripts/gazebo.material \
    /usr/share/gazebo-11/media/materials/scripts/GBuffer.material \
    /usr/share/gazebo-11/media/materials/scripts/grid.material \
    /usr/share/gazebo-11/media/materials/scripts/kitchen.material \
    /usr/share/gazebo-11/media/materials/scripts/lens_flare.compositor \
    /usr/share/gazebo-11/media/materials/scripts/Modulate.material \
    /usr/share/gazebo-11/media/materials/scripts/noise.compositor \
    /usr/share/gazebo-11/media/materials/scripts/oculus.material \
    /usr/share/gazebo-11/media/materials/scripts/perpixel.program \
    /usr/share/gazebo-11/media/materials/scripts/picker.material \
    /usr/share/gazebo-11/media/materials/scripts/point_light_shadow_demo.material \
    /usr/share/gazebo-11/media/materials/scripts/ShadowCaster.material \
    /usr/share/gazebo-11/media/materials/scripts/shadow_caster.program \
    /usr/share/gazebo-11/media/materials/scripts/shadow_caster_ignore_heightmap.program \
    /usr/share/gazebo-11/media/materials/scripts/ShadowCaster.program \
    /usr/share/gazebo-11/media/materials/scripts/spotlight_shadow_demo.material \
    /usr/share/gazebo-11/media/materials/scripts/ssao.compositor \
    /usr/share/gazebo-11/media/materials/scripts/ssao.material \
    /usr/share/gazebo-11/media/materials/scripts/SSAOPost.compositor \
    /usr/share/gazebo-11/media/materials/scripts/SSAOPost.material \
    /usr/share/gazebo-11/media/materials/scripts/StdQuad_vp.program \
    /usr/share/gazebo-11/media/materials/scripts/VPL.material \
    /usr/share/gazebo-11/media/materials/scripts/VPL.program \
    /usr/share/gazebo-11/media/materials/scripts/deform.material \
    /usr/share/gazebo-11/media/materials/scripts/WideCameraLensMap.compositor \
    /usr/share/gazebo-11/media/materials/textures/beigeWall.jpg \
    /usr/share/gazebo-11/media/materials/textures/building_frame.png \
    /usr/share/gazebo-11/media/materials/textures/bricks.png \
    /usr/share/gazebo-11/media/materials/textures/ceiling_tiled.jpg \
    /usr/share/gazebo-11/media/materials/textures/clouds.jpg \
    /usr/share/gazebo-11/media/materials/textures/com.png \
    /usr/share/gazebo-11/media/materials/textures/dirt_diffusespecular.png \
    /usr/share/gazebo-11/media/materials/textures/dirt_normal.png \
    /usr/share/gazebo-11/media/materials/textures/flat_normal.png \
    /usr/share/gazebo-11/media/materials/textures/fungus_diffusespecular.png \
    /usr/share/gazebo-11/media/materials/textures/fungus_normal.png \
    /usr/share/gazebo-11/media/materials/textures/granite2.jpg \
    /usr/share/gazebo-11/media/materials/textures/granite.jpg \
    /usr/share/gazebo-11/media/materials/textures/grass_diffusespecular.png \
    /usr/share/gazebo-11/media/materials/textures/grass.jpg \
    /usr/share/gazebo-11/media/materials/textures/grass_normal.png \
    /usr/share/gazebo-11/media/materials/textures/hardwood_floor.jpg \
    /usr/share/gazebo-11/media/materials/textures/heightmap_bowl.png \
    /usr/share/gazebo-11/media/materials/textures/heightmap_valley.png \
    /usr/share/gazebo-11/media/materials/textures/motorway.jpg \
    /usr/share/gazebo-11/media/materials/textures/paintedWall.jpg \
    /usr/share/gazebo-11/media/materials/textures/pioneerBody.jpg \
    /usr/share/gazebo-11/media/materials/textures/primary.jpg \
    /usr/share/gazebo-11/media/materials/textures/projection_filter.png \
    /usr/share/gazebo-11/media/materials/textures/rand1x32.png \
    /usr/share/gazebo-11/media/materials/textures/random.png \
    /usr/share/gazebo-11/media/materials/textures/residential.jpg \
    /usr/share/gazebo-11/media/materials/textures/road1.jpg \
    /usr/share/gazebo-11/media/materials/textures/runway.png \
    /usr/share/gazebo-11/media/materials/textures/secondary.jpg \
    /usr/share/gazebo-11/media/materials/textures/sidewalk.jpg \
    /usr/share/gazebo-11/media/materials/textures/steps.jpeg \
    /usr/share/gazebo-11/media/materials/textures/stereo_projection_pattern_high_res.png \
    /usr/share/gazebo-11/media/materials/textures/stereo_projection_pattern_high_res_red.png \
    /usr/share/gazebo-11/media/materials/textures/terrain_detail.jpg \
    /usr/share/gazebo-11/media/materials/textures/terrain.png \
    /usr/share/gazebo-11/media/materials/textures/trunk.jpg \
    /usr/share/gazebo-11/media/materials/textures/white.bmp \
    /usr/share/gazebo-11/media/materials/textures/willowMap.png \
    /usr/share/gazebo-11/media/materials/textures/wood.jpg \
    /usr/share/gazebo-11/media/materials/textures/WoodPallet.png \
    /usr/share/gazebo-11/media/models/cmu-13_26.bvh \
    /usr/share/gazebo-11/media/models/moonwalk.dae \
    /usr/share/gazebo-11/media/models/run.dae \
    /usr/share/gazebo-11/media/models/sit_down.dae \
    /usr/share/gazebo-11/media/models/sitting.dae \
    /usr/share/gazebo-11/media/models/stand_up.dae \
    /usr/share/gazebo-11/media/models/stand.dae \
    /usr/share/gazebo-11/media/models/sub_16.dae \
    /usr/share/gazebo-11/media/models/talk_a.dae \
    /usr/share/gazebo-11/media/models/talk_b.dae \
    /usr/share/gazebo-11/media/models/walk.dae \
    /usr/share/gazebo-11/media/rtshaderlib/FFPLib_Common.glsl \
    /usr/share/gazebo-11/media/rtshaderlib/FFPLib_Fog.glsl \
    /usr/share/gazebo-11/media/rtshaderlib/FFPLib_Lighting.glsl \
    /usr/share/gazebo-11/media/rtshaderlib/FFPLib_Texturing.glsl \
    /usr/share/gazebo-11/media/rtshaderlib/FFPLib_Transform.glsl \
    /usr/share/gazebo-11/media/rtshaderlib/SampleLib_ReflectionMap.glsl \
    /usr/share/gazebo-11/media/rtshaderlib/SGXLib_IntegratedPSSM.glsl \
    /usr/share/gazebo-11/media/rtshaderlib/SGXLib_NormalMapLighting.glsl \
    /usr/share/gazebo-11/media/rtshaderlib/SGXLib_PerPixelLighting.glsl \
    /usr/share/gazebo-11/media/skyx/CloudsNormal.png \
    /usr/share/gazebo-11/media/skyx/Clouds.png \
    /usr/share/gazebo-11/media/skyx/CloudsTile.png \
    /usr/share/gazebo-11/media/skyx/CMakeLists.txt \
    /usr/share/gazebo-11/media/skyx/Noise.jpg \
    /usr/share/gazebo-11/media/skyx/SkyX_Clouds.fragment \
    /usr/share/gazebo-11/media/skyx/SkyX_Clouds.hlsl \
    /usr/share/gazebo-11/media/skyx/SkyX_Clouds.vertex \
    /usr/share/gazebo-11/media/skyx/SkyX_Ground.fragment \
    /usr/share/gazebo-11/media/skyx/SkyX_Ground.hlsl \
    /usr/share/gazebo-11/media/skyx/SkyX_Ground.vertex \
    /usr/share/gazebo-11/media/skyx/SkyX_Lightning.fragment \
    /usr/share/gazebo-11/media/skyx/SkyX_Lightning.hlsl \
    /usr/share/gazebo-11/media/skyx/SkyX_Lightning.vertex \
    /usr/share/gazebo-11/media/skyx/SkyX.material \
    /usr/share/gazebo-11/media/skyx/SkyX_Moon.fragment \
    /usr/share/gazebo-11/media/skyx/SkyX_MoonHalo.png \
    /usr/share/gazebo-11/media/skyx/SkyX_Moon.hlsl \
    /usr/share/gazebo-11/media/skyx/SkyX_Moon.png \
    /usr/share/gazebo-11/media/skyx/SkyX_Moon.vertex \
    /usr/share/gazebo-11/media/skyx/SkyX_Skydome.fragment \
    /usr/share/gazebo-11/media/skyx/SkyX_Skydome.hlsl \
    /usr/share/gazebo-11/media/skyx/SkyX_Skydome.vertex \
    /usr/share/gazebo-11/media/skyx/SkyX_Starfield.png \
    /usr/share/gazebo-11/media/skyx/SkyX_VolClouds.fragment \
    /usr/share/gazebo-11/media/skyx/SkyX_VolClouds.hlsl \
    /usr/share/gazebo-11/media/skyx/SkyX_VolClouds_Lightning.fragment \
    /usr/share/gazebo-11/media/skyx/SkyX_VolClouds_Lightning.hlsl \
    /usr/share/gazebo-11/media/skyx/SkyX_VolClouds_Lightning.vertex \
    /usr/share/gazebo-11/media/skyx/SkyX_VolClouds.vertex \
    /usr/share/gazebo-11/worlds/actor.world \
    /usr/share/gazebo-11/worlds/actor_bvh.world \
    /usr/share/gazebo-11/worlds/animated_box.world \
    /usr/share/gazebo-11/worlds/animation_tension.world \
    /usr/share/gazebo-11/worlds/attach_lights.world \
    /usr/share/gazebo-11/worlds/blank.world \
    /usr/share/gazebo-11/worlds/blink_visual.world \
    /usr/share/gazebo-11/worlds/cafe.world \
    /usr/share/gazebo-11/worlds/camera.world \
    /usr/share/gazebo-11/worlds/camera_intrinsics.world \
    /usr/share/gazebo-11/worlds/cart_demo.world \
    /usr/share/gazebo-11/worlds/cessna_demo.world \
    /usr/share/gazebo-11/worlds/collision_zero.world \
    /usr/share/gazebo-11/worlds/contact.world \
    /usr/share/gazebo-11/worlds/contain_plugin_demo.world \
    /usr/share/gazebo-11/worlds/contain_plugin_moving_demo.world \
    /usr/share/gazebo-11/worlds/deform_visual.world \
    /usr/share/gazebo-11/worlds/depth_camera.world \
    /usr/share/gazebo-11/worlds/depth_camera2.world \
    /usr/share/gazebo-11/worlds/elevator.world \
    /usr/share/gazebo-11/worlds/empty.world \
    /usr/share/gazebo-11/worlds/empty_1_0.world \
    /usr/share/gazebo-11/worlds/empty_bullet.world \
    /usr/share/gazebo-11/worlds/empty_sky.world \
    /usr/share/gazebo-11/worlds/everything.world \
    /usr/share/gazebo-11/worlds/fiducial.world \
    /usr/share/gazebo-11/worlds/flash_light_plugin_demo.world \
    /usr/share/gazebo-11/worlds/flocking.world \
    /usr/share/gazebo-11/worlds/force_torque_demo.world \
    /usr/share/gazebo-11/worlds/friction_demo.world \
    /usr/share/gazebo-11/worlds/friction_pyramid.world \
    /usr/share/gazebo-11/worlds/fuel_models.world \
    /usr/share/gazebo-11/worlds/gravity_compensation.world \
    /usr/share/gazebo-11/worlds/gripper.world \
    /usr/share/gazebo-11/worlds/harness.world \
    /usr/share/gazebo-11/worlds/heightmap.world \
    /usr/share/gazebo-11/worlds/heightmap_dem.world \
    /usr/share/gazebo-11/worlds/hydra_demo.world \
    /usr/share/gazebo-11/worlds/imu_demo.world \
    /usr/share/gazebo-11/worlds/init_joint_control.world \
    /usr/share/gazebo-11/worlds/initial_velocity.world \
    /usr/share/gazebo-11/worlds/iris_arducopter_demo.world \
    /usr/share/gazebo-11/worlds/joint_damping_demo.world \
    /usr/share/gazebo-11/worlds/joint_friction_demo.world \
    /usr/share/gazebo-11/worlds/joints.world \
    /usr/share/gazebo-11/worlds/joy_demo.world \
    /usr/share/gazebo-11/worlds/keys_to_cmd_vel.world \
    /usr/share/gazebo-11/worlds/led_plugin_demo.world \
    /usr/share/gazebo-11/worlds/lensflare_plugin.world \
    /usr/share/gazebo-11/worlds/lensflare_wideangle_cam.world \
    /usr/share/gazebo-11/worlds/lift_drag_demo.world \
    /usr/share/gazebo-11/worlds/lights.world \
    /usr/share/gazebo-11/worlds/linear_battery_demo.world \
    /usr/share/gazebo-11/worlds/logical_camera.world \
    /usr/share/gazebo-11/worlds/lookat_demo.world \
    /usr/share/gazebo-11/worlds/magnetometer.world \
    /usr/share/gazebo-11/worlds/mass_on_rails.world \
    /usr/share/gazebo-11/worlds/misalignment_plugin_demo.world \
    /usr/share/gazebo-11/worlds/mud.world \
    /usr/share/gazebo-11/worlds/mud_bitmask.world \
    /usr/share/gazebo-11/worlds/multilink_shape.world \
    /usr/share/gazebo-11/worlds/nested_model.world \
    /usr/share/gazebo-11/worlds/nested_multilink_shape.world \
    /usr/share/gazebo-11/worlds/openal.world \
    /usr/share/gazebo-11/worlds/ortho.world \
    /usr/share/gazebo-11/worlds/osrf_elevator.world \
    /usr/share/gazebo-11/worlds/pioneer2dx.world \
    /usr/share/gazebo-11/worlds/pioneer2dx_camera.world \
    /usr/share/gazebo-11/worlds/pioneer2dx_laser.world \
    /usr/share/gazebo-11/worlds/pioneer2dx_laser_camera.world \
    /usr/share/gazebo-11/worlds/plane_demo.world \
    /usr/share/gazebo-11/worlds/plane_propeller_demo.world \
    /usr/share/gazebo-11/worlds/plot3d.world \
    /usr/share/gazebo-11/worlds/plugin.world \
    /usr/share/gazebo-11/worlds/point_light_shadows_demo.world \
    /usr/share/gazebo-11/worlds/polyline.world \
    /usr/share/gazebo-11/worlds/population.world \
    /usr/share/gazebo-11/worlds/pr2.world \
    /usr/share/gazebo-11/worlds/presentation.world \
    /usr/share/gazebo-11/worlds/pressure_sensor.world \
    /usr/share/gazebo-11/worlds/profiler.world \
    /usr/share/gazebo-11/worlds/projector.world \
    /usr/share/gazebo-11/worlds/random_velocity.world \
    /usr/share/gazebo-11/worlds/ray_cpu.world \
    /usr/share/gazebo-11/worlds/ray_noise_plugin.world \
    /usr/share/gazebo-11/worlds/reflectance.world \
    /usr/share/gazebo-11/worlds/road.world \
    /usr/share/gazebo-11/worlds/road_textures.world \
    /usr/share/gazebo-11/worlds/robocup09_spl_field.world \
    /usr/share/gazebo-11/worlds/robocup14_spl_field.world \
    /usr/share/gazebo-11/worlds/robocup_3Dsim.world \
    /usr/share/gazebo-11/worlds/rubble.world \
    /usr/share/gazebo-11/worlds/seesaw.world \
    /usr/share/gazebo-11/worlds/shapes.world \
    /usr/share/gazebo-11/worlds/shapes_bitmask.world \
    /usr/share/gazebo-11/worlds/shapes_layers.world \
    /usr/share/gazebo-11/worlds/shapes_shininess.world \
    /usr/share/gazebo-11/worlds/sim_events.world \
    /usr/share/gazebo-11/worlds/simple_arm.world \
    /usr/share/gazebo-11/worlds/simple_arm_teleop.world \
    /usr/share/gazebo-11/worlds/simple_gripper.world \
    /usr/share/gazebo-11/worlds/single_rotor_demo.world \
    /usr/share/gazebo-11/worlds/sonar_demo.world \
    /usr/share/gazebo-11/worlds/sphere_atlas_demo.world \
    /usr/share/gazebo-11/worlds/spotlight_shadows_demo.world \
    /usr/share/gazebo-11/worlds/ssao_plugin.world \
    /usr/share/gazebo-11/worlds/stacks.world \
    /usr/share/gazebo-11/worlds/static_map_plugin.world \
    /usr/share/gazebo-11/worlds/timer_gui.world \
    /usr/share/gazebo-11/worlds/torsional_friction_demo.world \
    /usr/share/gazebo-11/worlds/touch_plugin_demo.world \
    /usr/share/gazebo-11/worlds/tracked_vehicle_simple.world \
    /usr/share/gazebo-11/worlds/tracked_vehicle_wheeled.world \
    /usr/share/gazebo-11/worlds/transporter.world \
    /usr/share/gazebo-11/worlds/trigger.world \
    /usr/share/gazebo-11/worlds/twin_rotor_demo.world \
    /usr/share/gazebo-11/worlds/underwater.world \
    /usr/share/gazebo-11/worlds/variable_gearbox_plugin.world \
    /usr/share/gazebo-11/worlds/willowgarage.world \
    /usr/share/gazebo-11/worlds/wind_demo.world \
    /usr/share/gazebo-11/worlds/wireless_sensors.world \
    /usr/share/gazebo-11/worlds/zephyr_demo.world \
    /usr/share/gazebo-11/models/ground_plane \
    /usr/share/gazebo-11/models/sun \
    /usr/share/gazebo-11/models/ground_plane/model.config \
    /usr/share/gazebo-11/models/ground_plane/model.sdf \
    /usr/share/gazebo-11/models/sun/model.config \
    /usr/share/gazebo-11/models/sun/model.sdf \
    /usr/share/gazebo/setup.sh \
    /usr/share/gazebo/setup.bash \
    /usr/lib/gazebo-11/plugins/libTrackedVehiclePlugin.so \
    /usr/lib/gazebo-11/plugins/libActorPlugin.so \
    /usr/lib/gazebo-11/plugins/libActuatorPlugin.so \
    /usr/lib/gazebo-11/plugins/libAmbientOcclusionVisualPlugin.so \
    /usr/lib/gazebo-11/plugins/libArduCopterPlugin.so \
    /usr/lib/gazebo-11/plugins/libArrangePlugin.so \
    /usr/lib/gazebo-11/plugins/libAttachLightPlugin.so \
    /usr/lib/gazebo-11/plugins/libBlinkVisualPlugin.so \
    /usr/lib/gazebo-11/plugins/libBreakableJointPlugin.so \
    /usr/lib/gazebo-11/plugins/libBuoyancyPlugin.so \
    /usr/lib/gazebo-11/plugins/libCameraPlugin.so \
    /usr/lib/gazebo-11/plugins/libCartDemoPlugin.so \
    /usr/lib/gazebo-11/plugins/libCessnaPlugin.so \
    /usr/lib/gazebo-11/plugins/libContactPlugin.so \
    /usr/lib/gazebo-11/plugins/libContainPlugin.so \
    /usr/lib/gazebo-11/plugins/libDepthCameraPlugin.so \
    /usr/lib/gazebo-11/plugins/libDiffDrivePlugin.so \
    /usr/lib/gazebo-11/plugins/libFiducialCameraPlugin.so \
    /usr/lib/gazebo-11/plugins/libFlashLightPlugin.so \
    /usr/lib/gazebo-11/plugins/libFollowerPlugin.so \
    /usr/lib/gazebo-11/plugins/libForceTorquePlugin.so \
    /usr/lib/gazebo-11/plugins/libGimbalSmall2dPlugin.so \
    /usr/lib/gazebo-11/plugins/libGpuRayPlugin.so \
    /usr/lib/gazebo-11/plugins/libHarnessPlugin.so \
    /usr/lib/gazebo-11/plugins/libHeightmapLODPlugin.so \
    /usr/lib/gazebo-11/plugins/libImuSensorPlugin.so \
    /usr/lib/gazebo-11/plugins/libInitialVelocityPlugin.so \
    /usr/lib/gazebo-11/plugins/libJointControlPlugin.so \
    /usr/lib/gazebo-11/plugins/libJointTrajectoryPlugin.so \
    /usr/lib/gazebo-11/plugins/libKeysToCmdVelPlugin.so \
    /usr/lib/gazebo-11/plugins/libKeysToJointsPlugin.so \
    /usr/lib/gazebo-11/plugins/libLedPlugin.so \
    /usr/lib/gazebo-11/plugins/libLensFlareSensorPlugin.so \
    /usr/lib/gazebo-11/plugins/libLiftDragPlugin.so \
    /usr/lib/gazebo-11/plugins/libLinearBatteryConsumerPlugin.so \
    /usr/lib/gazebo-11/plugins/libLinearBatteryPlugin.so \
    /usr/lib/gazebo-11/plugins/libLinkPlot3DPlugin.so \
    /usr/lib/gazebo-11/plugins/libMisalignmentPlugin.so \
    /usr/lib/gazebo-11/plugins/libModelPropShop.so \
    /usr/lib/gazebo-11/plugins/libMudPlugin.so \
    /usr/lib/gazebo-11/plugins/libPlaneDemoPlugin.so \
    /usr/lib/gazebo-11/plugins/libPressurePlugin.so \
    /usr/lib/gazebo-11/plugins/libRayPlugin.so \
    /usr/lib/gazebo-11/plugins/libRaySensorNoisePlugin.so \
    /usr/lib/gazebo-11/plugins/libReflectancePlugin.so \
    /usr/lib/gazebo-11/plugins/libRubblePlugin.so \
    /usr/lib/gazebo-11/plugins/libShaderParamVisualPlugin.so \
    /usr/lib/gazebo-11/plugins/libSimpleTrackedVehiclePlugin.so \
    /usr/lib/gazebo-11/plugins/libSkidSteerDrivePlugin.so \
    /usr/lib/gazebo-11/plugins/libSonarPlugin.so \
    /usr/lib/gazebo-11/plugins/libSphereAtlasDemoPlugin.so \
    /usr/lib/gazebo-11/plugins/libStaticMapPlugin.so \
    /usr/lib/gazebo-11/plugins/libStopWorldPlugin.so \
    /usr/lib/gazebo-11/plugins/libTouchPlugin.so \
    /usr/lib/gazebo-11/plugins/libVariableGearboxPlugin.so \
    /usr/lib/gazebo-11/plugins/libVehiclePlugin.so \
    /usr/lib/gazebo-11/plugins/libWheelSlipPlugin.so \
    /usr/lib/gazebo-11/plugins/libWheelTrackedVehiclePlugin.so \
    /usr/lib/gazebo-11/plugins/libWindPlugin.so \
    /usr/lib/gazebo-11/plugins/libHydraPlugin.so \
    /usr/lib/gazebo-11/plugins/libHydraDemoPlugin.so \
    /usr/lib/gazebo-11/plugins/libJoyPlugin.so \
    /usr/lib/gazebo-11/plugins/libElevatorPlugin.so \
    /usr/lib/gazebo-11/plugins/libRandomVelocityPlugin.so \
    /usr/lib/gazebo-11/plugins/libTransporterPlugin.so \
    /usr/lib/gazebo-11/plugins/libCessnaGUIPlugin.so \
    /usr/lib/gazebo-11/plugins/libKeyboardGUIPlugin.so \
    /usr/lib/gazebo-11/plugins/libLookAtDemoPlugin.so \
    /usr/lib/gazebo-11/plugins/libTimerGUIPlugin.so \
    /usr/lib/gazebo-11/plugins/libGravityCompensationPlugin.so \
    /usr/lib/gazebo-11/plugins/libSimEventsPlugin.so \
    /usr/lib/gazebo-11/plugins/libRegionEventBoxPlugin.so \
    /usr/lib/gazebo-11/plugins/libRestWebPlugin.so \
    /usr/lib/gazebo-11/plugins/libRestUiPlugin.so \
"

INSANE_SKIP:${PN}:append = " dev-deps"

BBCLASSEXTEND = "native nativesdk"
