SUMMARY = "Dart Physics Engine"
DESCRIPTION = "${SUMMARY}"
LICENSE = "BSD-2-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=2a461be67a1edf991251f85f3aadd1d0"

SRC_URI = "git://github.com/gazebosim/gz-sim/;branch=ign-gazebo6;protocol=https"
SRCREV = "8a4bc3082b3f536ef6e53d137724794073a7b5bc"
S = "${WORKDIR}/git"

DEPENDS = " \
    protobuf \
    protobuf-native \
    python3-native \
    python3 \
    python3-pybind11 \
    gz-cmake2 \
    gz-plugin1 \
    gz-transport11 \
    gz-msgs8 \
    gz-common4 \
    gz-fuel-tools7 \
    gz-gui6 \
    gz-physics5 \
    gz-sensors6 \
    gz-rendering6 \
    gz-math6 \
    gz-tools1 \
    gz-utils1 \
    sdformat12 \
"

inherit cmake pkgconfig cmake_qt5

EXTRA_OECMAKE:append:class-target = " \
    -DBUILD_TESTING=OFF \
    -DPROTOBUF_PROTOC_EXECUTABLE=${WORKDIR}/recipe-sysroot-native/usr/bin/protoc \
    -DPython_LIBRARY:FILEPATH=${WORKDIR}/recipe-sysroot/usr/lib \
"

FILES:${PN}:append = " \
    /usr/share \
    /usr/lib/ruby \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-ackermann-steering-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-ackermann-steering-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-ackermann-steering-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-ackermann-steering-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-air-pressure-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-air-pressure-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-air-pressure-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-air-pressure-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-altimeter-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-altimeter-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-altimeter-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-altimeter-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-apply-joint-force-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-apply-joint-force-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-apply-joint-force-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-apply-joint-force-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-apply-link-wrench-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-apply-link-wrench-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-apply-link-wrench-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-apply-link-wrench-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-linearbatteryplugin-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-linearbatteryplugin-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-linearbatteryplugin-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-linearbatteryplugin-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-breadcrumbs-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-breadcrumbs-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-breadcrumbs-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-breadcrumbs-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-buoyancy-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-buoyancy-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-buoyancy-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-buoyancy-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-buoyancy-engine-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-buoyancy-engine-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-buoyancy-engine-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-buoyancy-engine-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-collada-world-exporter-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-collada-world-exporter-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-collada-world-exporter-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-collada-world-exporter-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-comms-endpoint-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-comms-endpoint-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-comms-endpoint-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-comms-endpoint-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-contact-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-contact-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-contact-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-contact-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-camera-video-recorder-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-camera-video-recorder-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-camera-video-recorder-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-camera-video-recorder-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-detachable-joint-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-detachable-joint-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-detachable-joint-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-detachable-joint-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-diff-drive-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-diff-drive-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-diff-drive-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-diff-drive-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-elevator-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-elevator-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-elevator-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-elevator-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-follow-actor-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-follow-actor-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-follow-actor-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-follow-actor-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-forcetorque-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-forcetorque-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-forcetorque-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-forcetorque-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-hydrodynamics-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-hydrodynamics-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-hydrodynamics-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-hydrodynamics-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-imu-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-imu-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-imu-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-imu-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-controller-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-controller-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-controller-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-joint-controller-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-position-controller-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-position-controller-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-position-controller-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-joint-position-controller-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-state-publisher-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-state-publisher-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-state-publisher-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-joint-state-publisher-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-trajectory-controller-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-trajectory-controller-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-joint-trajectory-controller-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-joint-trajectory-controller-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-kinetic-energy-monitor-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-kinetic-energy-monitor-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-kinetic-energy-monitor-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-kinetic-energy-monitor-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-label-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-label-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-label-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-label-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-lift-drag-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-lift-drag-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-lift-drag-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-lift-drag-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-log-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-log-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-log-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-log-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-log-video-recorder-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-log-video-recorder-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-log-video-recorder-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-log-video-recorder-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-logicalaudiosensorplugin-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-logicalaudiosensorplugin-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-logicalaudiosensorplugin-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-logicalaudiosensorplugin-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-logical-camera-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-logical-camera-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-logical-camera-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-logical-camera-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-magnetometer-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-magnetometer-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-magnetometer-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-magnetometer-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-mecanum-drive-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-model-photo-shoot-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-model-photo-shoot-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-model-photo-shoot-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-model-photo-shoot-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-mecanum-drive-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-mecanum-drive-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-mecanum-drive-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-multicopter-motor-model-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-multicopter-motor-model-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-multicopter-motor-model-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-multicopter-motor-model-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-multicopter-control-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-multicopter-control-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-multicopter-control-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-multicopter-control-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-navsat-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-navsat-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-navsat-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-navsat-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-odometry-publisher-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-odometry-publisher-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-odometry-publisher-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-odometry-publisher-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-opticaltactileplugin-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-opticaltactileplugin-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-opticaltactileplugin-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-opticaltactileplugin-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-particle-emitter-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-particle-emitter-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-particle-emitter-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-particle-emitter-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-particle-emitter2-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-particle-emitter2-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-particle-emitter2-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-particle-emitter2-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-performer-detector-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-performer-detector-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-performer-detector-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-performer-detector-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-perfect-comms-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-perfect-comms-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-perfect-comms-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-perfect-comms-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-physics-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-physics-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-physics-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-physics-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-pose-publisher-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-pose-publisher-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-pose-publisher-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-pose-publisher-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-rf-comms-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-rf-comms-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-rf-comms-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-rf-comms-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-scene-broadcaster-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-scene-broadcaster-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-scene-broadcaster-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-scene-broadcaster-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-sensors-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-sensors-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-sensors-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-sensors-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-shader-param-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-shader-param-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-shader-param-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-shader-param-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-thermal-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-thermal-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-thermal-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-thermal-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-thermal-sensor-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-thermal-sensor-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-thermal-sensor-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-thermal-sensor-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-thruster-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-thruster-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-thruster-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-thruster-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-touchplugin-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-touchplugin-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-touchplugin-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-touchplugin-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-track-controller-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-track-controller-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-track-controller-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-track-controller-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-tracked-vehicle-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-tracked-vehicle-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-tracked-vehicle-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-tracked-vehicle-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-trajectory-follower-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-trajectory-follower-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-trajectory-follower-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-trajectory-follower-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-triggered-publisher-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-triggered-publisher-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-triggered-publisher-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-triggered-publisher-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-user-commands-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-user-commands-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-user-commands-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-user-commands-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-velocity-control-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-velocity-control-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-velocity-control-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-velocity-control-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-wheel-slip-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-wheel-slip-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-wheel-slip-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-wheel-slip-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-wind-effects-system.so.6.14.0 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-wind-effects-system.so.6 \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo6-wind-effects-system.so \
    /usr/lib/ign-gazebo-6/plugins/libignition-gazebo-wind-effects-system.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libAlignTool.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libBananaForScale.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libComponentInspector.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libComponentInspectorEditor.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libCopyPaste.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libEntityContextMenuPlugin.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libEntityTree.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libJointPositionController.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libLights.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libPlaybackScrubber.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libPlot3D.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libPlotting.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libResourceSpawner.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libGzScene3D.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libSelectEntities.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libGzSceneManager.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libShapes.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libSpawn.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libTransformControl.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libVideoRecorder.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libViewAngle.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libVisualizationCapabilities.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libVisualizeContacts.so \
    /usr/lib/ign-gazebo-6/plugins/gui/libVisualizeLidar.so \
    /usr/lib/ign-gazebo-6/plugins/gui/IgnGazebo/libEntityContextMenu.so \
    /usr/lib/ign-gazebo-6/plugins/gui/IgnGazebo/qmldir \
    /usr/lib/ruby/ignition \
    /usr/lib/ruby/ignition/cmdgazebo6.rb \
    /usr/lib/ruby/ignition/cmdmodel6.rb \
    /usr/lib/python/sdformat.cpython-310-x86_64-linux-gnu.so \
    /usr/lib/python/ignition/gazebo.cpython-310-x86_64-linux-gnu.so \
    /usr/lib/python/ignition/common.cpython-310-x86_64-linux-gnu.so \
    /usr/share/ignition \
    /usr/share/gz \
    /usr/share/ignition/gazebo6.yaml \
    /usr/share/ignition/model6.yaml \
    /usr/share/ignition/ignition-gazebo6 \
    /usr/share/ignition/ignition-gazebo6/server.config \
    /usr/share/ignition/ignition-gazebo6/playback_server.config \
    /usr/share/ignition/ignition-gazebo6/gui \
    /usr/share/ignition/ignition-gazebo6/worlds \
    /usr/share/ignition/ignition-gazebo6/gui/gui.config \
    /usr/share/ignition/ignition-gazebo6/gui/playback_gui.config \
    /usr/share/ignition/ignition-gazebo6/worlds/3k_shapes.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/ackermann_steering.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/actor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/actor_crowd.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/actors_population.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/apply_joint_force.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/apply_link_wrench.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/auv_controls.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/boundingbox_camera.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/breadcrumbs.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/buoyancy.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/buoyancy_engine.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/camera_sensor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/camera_video_record_dbl_pendulum.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/collada_world_exporter.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/contact_sensor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/conveyor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/debug_shapes.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/default.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/depth_camera_sensor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/detachable_joint.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/diff_drive.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/diff_drive_skid.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/elevator.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/empty.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/empty_gui.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/follow_actor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/fuel.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/fuel_textured_mesh.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/gpu_lidar_retro_values_sensor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/gpu_lidar_sensor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/graded_buoyancy.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/grid.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/heightmap.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/import_mesh.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/joint_controller.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/joint_position_controller.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/joint_trajectory_controller.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/kinetic_energy_monitor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/levels.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/levels_no_performers.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/lift_drag.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/lift_drag_battery.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/lift_drag_nested.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/lightmap.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/lights.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/linear_battery_demo.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/log_record_dbl_pendulum.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/log_record_keyboard.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/log_record_resources.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/log_record_shapes.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/logical_audio_sensor_plugin.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/logical_camera_sensor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/mecanum_drive.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/minimal_scene.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/model_photo_shoot.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/multi_lrauv_race.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/multicopter_velocity_control.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/nested_model.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/optical_tactile_sensor_plugin.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/particle_emitter.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/particle_emitter2.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/pendulum_links.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/perfect_comms.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/performer_detector.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/physics_options.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/plane_propeller_demo.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/plot_3d.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/polylines.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/pose_publisher.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/quadcopter.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/resource_spawner.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/rf_comms.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/rolling_shapes.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/segmentation_camera.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/sensors.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/sensors_demo.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/shader_param.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/shapes.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/shapes_bitmask.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/skid_steer_mecanum.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/sky.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/spaces.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/spherical_coordinates.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/thermal_camera.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/touch_plugin.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/track_drive.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/tracked_vehicle_simple.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/trajectory_follower.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/triggered_camera_sensor.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/triggered_publisher.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/trisphere_cycle_wheel_slip.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/tunnel.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/velocity_control.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/video_record_dbl_pendulum.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/visibility.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/visualize_contacts.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/visualize_lidar.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/wind.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/world_joint.sdf \
    /usr/share/ignition/ignition-gazebo6/worlds/thumbnails \
    /usr/share/ignition/ignition-gazebo6/worlds/thumbnails/OpenRobotics.NAO joint control.png \
    /usr/share/ignition/ignition-gazebo6/worlds/thumbnails/OpenRobotics.Panda joint control world.png \
    /usr/share/ignition/ignition-gazebo6/worlds/thumbnails/OpenRobotics.Prius on Sonoma Raceway.png \
    /usr/share/ignition/ignition-gazebo6/worlds/thumbnails/OpenRobotics.Quadcopter teleop.png \
    /usr/share/ignition/ignition-gazebo6/worlds/thumbnails/OpenRobotics.Tugbot in Warehouse.png \
    /usr/share/ignition/ignition-gazebo6/worlds/thumbnails/openrobotics.empty.png \
    /usr/share/gz/gz1.completion.d \
    /usr/share/gz/gz1.completion.d/gazebo6.bash_completion.sh \
    /usr/share/gz/gz1.completion.d/model6.bash_completion.sh \
"

INSANE_SKIP:${PN}:append = " dev-so"

BBCLASSEXTEND = "native nativesdk"
